# Site settings
title: jenkins-highfive-theme
email: jameel@highfive.com
description: Beautify your Jenkins with the Highfive theme!
meta_title: Jenkins Theme - jenkins-highfive-theme
meta_description: Beautify your Jenkins with the Highfive theme! So you love Jenkins but hate its ugly user interface and icons… Me too! Introducing a Jenkins Theme based on Material Design. You can turn your favorite frog CI tool into a handsome prince in few steps!

baseurl: ""
url: "https://parlaylabs.github.io/jenkins-highfive-theme"
github_url: "https://github.com/parlaylabs/jenkins-highfive-theme"


# Build settings
markdown: kramdown

exclude: [node_modules, package.json, npm-debug.log, Gruntfile.js, scss]

gems:
    - jekyll-minifier
